<template>
  <div class="pokemon__wrapper">
    <img class="pokemon slide-in-blurred-top" :src="sprite">
    <div class="pokemon__surface"></div>
  </div>
</template>

<script>
export default {
  name: "Pokemon",
  props: {
    sprite: {
      type: String
    }
  }
};
</script>

<style scoepd lang="scss">
.pokemon__wrapper {
  display: flex;
  flex-direction: column;
  align-items: center;
  position: relative;
  .pokemon {
    position: absolute;
    bottom: 75px;
    z-index: 3;
    transform: scale(1.5);
  }
  .pokemon__surface {
    position: absolute;
    bottom: 0;
    width: 200px;
    height: 200px;
    background-color: #edf5e4;
    border: 10px solid #d9d9d9;
    border-radius: 50%;
    transform: rotateX(70deg) rotate(0);
    transform-style: preserve-3d;
  }
}

.slide-in-blurred-top {
  animation: slide-in-blurred-top 0.5s cubic-bezier(0.23, 1, 0.32, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2019-6-14 13:24:54
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-blurred-top
 * ----------------------------------------
 */
@keyframes slide-in-blurred-top {
  0% {
    transform: translateY(-1000px) scaleY(2.5) scaleX(0.2);
    transform-origin: 50% 0%;
    filter: blur(40px);
    opacity: 0;
  }
  100% {
    transform: translateY(0) scaleY(1) scaleX(1);
    transform-origin: 50% 50%;
    filter: blur(0);
    opacity: 1;
  }
}
</style>
